Feature home
umiatiyah/my-portfolio-reactapp pull request #2
Opened 2023-08-16 02:13 UTC by umiatiyah

how about this page?
![image](https://github.com/umiatiyah/my-portfolio-reactapp/assets/78152106/dbbc8e78-7515-4fac-8413-2480f2449bc8)

need your suggestion for structure code
![image](https://github.com/umiatiyah/my-portfolio-reactapp/assets/78152106/33cb60f5-daa1-4283-9658-83c60a07c187)

2023-08-16 04:22 UTC, fathrezza146 commented
each components in home should be wrapped in folders, in case you need any hooks for each section or need additional component inside

2023-08-16 04:23 UTC, fathrezza146 requested changes

2023-08-16 04:23 UTC, fathrezza146 commented on src/views/home/index.tsx
> +        <Navbar />
navbar, header, and footer can be placed at router

2023-08-16 17:45 UTC, umiatiyah commented on src/views/home/index.tsx
> +        <Navbar />
i've put it into router, please check

2023-08-16 17:56 UTC, umiatiyah commented
> each components in global or home should be wrapped in folders, in case you need any hooks for each section or need additional component inside.
> 
> For Layout please put it in components folder

ok, i've replace layout into components folder.
but I don't understand how about components in home, should I wrap all section into one file tsx? then all section home (about, contact, portfolio) in one file index.tsx in home

2023-08-17 14:39 UTC, fathrezza146 commented
> > each components in global or home should be wrapped in folders, in case you need any hooks for each section or need additional component inside.
> > For Layout please put it in components folder
> 
> ok, i've replace layout into components folder. but I don't understand how about components in home, should I wrap all section into one file tsx? then all section home (about, contact, portfolio) in one file index.tsx in home @fathrezza146

no, that is good. but each sectio (about, contact, porto) should each be a floder.

2023-08-17 15:45 UTC, fathrezza146 approved these changes
lets discuss about foldering later lmao. for now its good

2023-08-17 15:59 UTC, merged